name: BugBucks
services:
  mariadb:
    image: mariadb:11.7
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IdentityDb
      MYSQL_USER: IdentityDb_user
      MYSQL_PASSWORD: IdentityDb_password
    ports:
      - "3306:3306"
    networks:
      - bugbucks-net
    volumes:
      - mariadb_data:/var/lib/mysql
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/" ]
      interval: 5s
      retries: 5
    networks:
      - bugbucks-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - bugbucks-net
  
  
  #  loggingservice:
  #    build:
  #      context: ../
  #      dockerfile: ./src/Services/LoggingService/LoggingService.Api/Dockerfile
  #
  #    container_name: loggingservice
  #    ports:
  #      - "8080:8080"
  #    #environment:
  #    #  - ASPNETCORE_ENVIRONMENT=Development
  #    depends_on:
  #      elasticsearch:
  #        condition: service_healthy  # Wait for Elasticsearch status to become HEALTHY 
  #      
  #    networks:
  #      - bugbucks-net

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    command: server
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - vault_data:/vault/file
    networks:
      - bugbucks-net
  
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - bugbucks-net

networks:
  bugbucks-net:
    driver: bridge

volumes:
  mariadb_data:
  vault_data:

      
