name: BugBucks
services:
  loggingservice:
    build:
      context: ../
      dockerfile: ./src/Services/LoggingService/LoggingService.Api/Dockerfile

    container_name: loggingservice
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
