global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]   # collector internal metrics
  - job_name: 'services'
    static_configs:
      - targets:
          - 'bugbucks-gateway:8080'
          - 'bugbucks-identity-service:8080'
          - 'bugbucks-checkout-service:8080'
          - 'bugbucks-order-service:8080'
          - 'bugbucks-payment-service:8080'

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

remote_write:
  - url: "http://tempo:3200/api/prom/push"   # Tempo exemplars