server:
  http_listen_port: 3200

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

metrics_generator:
  storage:
    path: /tmp/tempo/metrics-generator
  ring:
    kvstore:
      store: memberlist


compactor:
  compaction:
    block_retention: 168h

