name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/bugbucks
  ASPNETCORE_ENVIRONMENT: Test
  ConnectionStrings__DefaultConnection: "Server=127.0.0.1;Port=3306;Database=IdentityService;Uid=root;Pwd=password;"

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:11.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: IdentityService
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        service:
          - src/Services/CheckoutService/CheckoutService.Api
          - src/Services/IdentityService/IdentityService.Api
          - src/Services/OrderService/OrderService.Api
          - src/Services/PaymentService/PaymentService.Api
          - src/Gateways/Gateway.Api
    steps:
      - uses: actions/checkout@v4

      - name: Log in GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}:${{ github.sha }}