name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}/bugbucks
  ASPNETCORE_ENVIRONMENT: Test
  ConnectionStrings__DefaultConnection: "Server=localhost;Port=3306;Database=IdentityService;Uid=root;Pwd=password;"
  RABBITMQ_HOST: rabbitmq
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:11.7
        env:
          MARIADB_ROOT_PASSWORD: password
          MARIADB_USER: user
          MARIADB_PASSWORD: password
          MARIADB_DATABASE: IdentityService
          MARIADB_AUTHENTICATION_PLUGIN: mysql_native_password 
          MARIADB_INNODB_USE_NATIVE_AIO: 0
          MARIADB_AUTO_UPGRADE: 1
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -uroot -ppassword" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --ulimit memlock=262144:262144
          --security-opt seccomp=unconfined


      rabbitmq:
        image: rabbitmq:4-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd="rabbitmqctl status"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test 
          --configuration Release
          --no-build
          --filter "FullyQualifiedName!~RabbitMqTopologyTests" 
          --logger "trx;LogFileName=test-results.trx"
        
       

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        service:
          - src/Services/CheckoutService/CheckoutService.Api
          - src/Services/IdentityService/IdentityService.Api
          - src/Services/OrderService/OrderService.Api
          - src/Services/PaymentService/PaymentService.Api
          - src/Gateways/Gateway.Api
    steps:
      - uses: actions/checkout@v4

      - name: Log in GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}:${{ github.sha }}